name: ASP.NET Core CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build with dotnet
      run: dotnet build --configuration Release samples/aspnetcore/mvc/domain/src/MvcSample/MvcSample.csproj
    - name: Test with dotnet
      run: dotnet test --configuration Release samples/aspnetcore/mvc/domain/test/**/*.csproj
    - name: Package with dotnet
      run: dotnet publish --configuration Release samples/aspnetcore/mvc/domain/src/MvcSample/MvcSample.csproj
    - name: Publish artifact
      uses: actions/upload-artifact@master
      with:
        name: webapp
        path: samples/aspnetcore/mvc/domain/src/MvcSample/bin/Release/netcoreapp2.2/publish